---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    # without this, deleting app won't delete res it manages.
    # To perform a casading delete, you must add the finalizer
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    # gitlab requires .git suffix
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    path: guestbook  # plain manifest files in this dir
    # optional, argod can detect path containers plain manifest files.
    directory:
      recurse: true  # default to false
      include: "*.yaml"  # default: .yaml, .yml, .json
      # include: "{*.yml,*.yaml}"
      # include: "mydir/*"
      # exclude: '{config.json,env-usw2/*}'
  destination:
    # server: 'https://kubernetes.default.svc'
    name: in-cluster
    namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
