---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    # without this, deleting app won't delete res it manages.
    # To perform a casading delete, you must add the finalizer
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    path: guestbook
    directory: {}
  destination:
    # server: 'https://kubernetes.default.svc'
    name: in-cluster
    namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
