---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: podinfo
  namespace: argocd  # app ns must be the same as argocd ns
  finalizers:
    # without this, deleting app won't delete res it manages.
    # To perform a casading delete, you must add the finalizer
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    chart: podinfo  # this tells argocd above url is a helm repo
    targetRevision: 6.5.3

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
